name: Setup EC2 Linux

description: Setup EC2 Linux

inputs:
  GITHUB_TOKEN:
    required: true

runs:
  using: composite
  steps:
    - name: Checkout PyTorch
      uses: pytorch/pytorch/.github/actions/checkout-pytorch@master
    - name: Setup Linux
      uses: ./.github/actions/setup-linux
    - name: Chown workspace
        run: |
          retry () {
              "$@"  || (sleep 1 && "$@") || (sleep 2 && "$@")
          }
          retry docker pull "${ALPINE_IMAGE}"
          # Ensure the working directory gets chowned back to the current user
          docker run --pull=never --rm -v "$(pwd)":/v -w /v "${ALPINE_IMAGE}" chown -R "$(id -u):$(id -g)" .
      - name: Clean workspace
      run: |
        rm -rf "${GITHUB_WORKSPACE}"
        mkdir "${GITHUB_WORKSPACE}"
    - name: "[FB EMPLOYEES] Enable SSH (Click me for login details)"
      uses: seemethere/add-github-ssh-key@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
