name: Checkout branch

description: Checks out the desired branch

inputs:
  repository:
    required: true
    description: 'Repository name with owner. For example, pytorch/pytorch'
    default: "pytorch/pytorch"
  branch:
    description: 'The branch, tag, or SHA to checkout'
  directory:
    description: 'Relative path under $GITHUB_WORKSPACE to place the repository'

runs:
  using: composite
  steps:
      - name: Checkout ${{ inputs.repository }}
        uses: zhouzhuojie/checkout@05b13c9a0d21f08f6d5e64a1d5042246d13619d9
        with:
          ref: ${{ inputs.branch || github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
          submodules: "recursive"
          repository: ${{ inputs.repository }}
          path: ${{ inputs.directory }}
      - name: Clean ${{ inputs.repository }} checkout
        run: |
          # Remove any artifacts from the previous checkouts
          git clean -fxd
        working-directory: ${{ inputs.directory }}
